Add methods
AliakseiKarpuk/CarRentDealOOPModel pull request #1
Opened 2021-07-26 09:31 UTC by AliakseiKarpuk

2021-07-27 13:08 UTC, vladimir-moshkov requested changes
Необходима доработка

2021-07-27 13:08 UTC, vladimir-moshkov commented on src/main/java/entity/Car.java
> +    private List<Car> carList;
Для чего в объекте хранить коллекцию таких же объектов? 

- [ ] Пояснить архитектурное решение, которого не было на схеме

2021-07-27 13:08 UTC, vladimir-moshkov commented on src/main/java/entity/CarRentDeal.java
> +import lombok.extern.log4j.Log4j;
- [ ] Зачем прикручены два логгера?

2021-07-27 13:08 UTC, vladimir-moshkov commented on src/main/java/entity/CarRentDeal.java
>  import java.util.Date;
- [ ] Убрать все неиспользуемые импорты

2021-07-27 13:08 UTC, vladimir-moshkov commented on src/main/java/entity/CarRentDeal.java
> +    public boolean verifyPickUpAndDropOffDate(LocalDate pickUpDate, LocalDate dropOffDate, LocalDate currentDate) {
- [ ] Нам где-то понадобится буленовский результат? Если да, то метод нужно назвать не verify, а как-то по-другому, в каких целях ты хочешь его использовать.

Если же это действительно verify, то лучше возвращать не boolean, а сразу использовать assertions

2021-08-05 06:57 UTC, AliakseiKarpuk commented on src/main/java/entity/CarRentDeal.java
> +    public boolean verifyPickUpAndDropOffDate(LocalDate pickUpDate, LocalDate dropOffDate, LocalDate currentDate) {
По сути этот буленовский результат возвращает true если на такую дату можно арендовать машину. И пользователь видит ошибку, если на выбранную дату нельзя взять машину

2021-08-05 06:57 UTC, AliakseiKarpuk commented on src/main/java/entity/CarRentDeal.java
>  import java.util.Date;
Удалил все неиспользуемые импорты

2021-08-05 06:57 UTC, AliakseiKarpuk commented on src/main/java/entity/CarRentDeal.java
> +import lombok.extern.log4j.Log4j;
Удалил второй логгер

2021-08-05 06:57 UTC, AliakseiKarpuk commented on src/main/java/entity/Car.java
> +    private List<Car> carList;
Удалил коллекцию, так как ее не было на схеме и она здесь по сути не нужна

2021-08-05 14:45 UTC, vladimir-moshkov approved these changes

2021-08-06 06:16 UTC, merged